# Generated by Django 3.2.16 on 2023-05-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastrequest',
            name='request',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pastrequest',
            name='response',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
