# Generated by Django 3.2.16 on 2023-07-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
