# Generated by Django 3.2.16 on 2023-05-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speach', '0002_auto_20230516_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastrequest',
            name='response',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
