# Generated by Django 3.2.16 on 2023-07-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speach', '0002_alter_company_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='service',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
