# Generated by Django 3.2.16 on 2023-05-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speach', '0003_alter_pastrequest_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
