# Generated by Django 4.2.6 on 2023-11-07 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('speach', '0004_auto_20230708_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='last_use_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userdata',
            name='uses_left',
            field=models.IntegerField(default=0),
        ),
    ]
