# Generated by Django 3.2.16 on 2023-06-22 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speach', '0005_feedback_feedbackfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speach.feedbacktopic'),
        ),
    ]
