# Generated by Django 4.2.6 on 2023-11-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speach', '0006_remove_userdata_last_use_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bonus_uses',
            field=models.IntegerField(default=0),
        ),
    ]
