# Generated by Django 4.2.6 on 2023-11-22 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djstripe', '0011_2_7'),
        ('speach', '0009_alter_discountcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(blank=True, default=123, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='user_redeemed',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='topic_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='speach.feedbacktopic'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer'),
        ),
    ]
