# Generated by Django 4.2.6 on 2023-11-22 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speach', '0010_alter_company_user_alter_discountcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='user_redeemed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
