# Generated by Django 3.2.16 on 2023-02-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField(default=0.0)),
                ('requests_per_day', models.IntegerField(default=10)),
            ],
        ),
    ]
