# Generated by Django 3.2.16 on 2023-02-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_paymentplans_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.paymentplans'),
        ),
    ]
