# Generated by Django 3.2.16 on 2023-02-25 21:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_userextended_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastrequest',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 21, 20, 50, 494582, tzinfo=utc)),
        ),
    ]
