# Generated by Django 3.2.16 on 2023-02-26 20:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230226_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 20, 48, 43, 707200, tzinfo=utc)),
        ),
    ]
