#!/bin/bash
set -e

#arguments
# Parse command-line arguments
while getopts "n" opt; do
  case $opt in
    n) no_cache="--no-cache";;
    \?) echo "Invalid option -$OPTARG" >&2;;
  esac
done

echo "no_cache: $no_cache"

workdir=$SP_HOME/docker/mysql

docker build $no_cache -t my-mysql-base:latest $workdir -f $workdir/base_docker
