#!/bin/bash
set -e

#arguments
# Parse command-line arguments
while getopts "n:" opt; do
  case $opt in
    n) no_cache="$OPTARG";;
    \?) echo "Invalid option -$OPTARG" >&2;;
  esac
done


workdir=$SP_HOME/src/

docker build $no_cache -t nginx_sp:latest $workdir -f $workdir/Dockerfile_nginx
