# Generated by Django 3.2.16 on 2023-05-07 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 10, 20, 35, 985143, tzinfo=utc)),
        ),
    ]
