# Generated by Django 3.2.16 on 2023-02-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_paymentplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplans',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
