# Generated by Django 3.2.16 on 2023-02-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userextended_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplans',
            name='available_to_select',
            field=models.BooleanField(default=False),
        ),
    ]
