# Generated by Django 3.2.16 on 2023-02-11 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_paymentplans_available_to_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='latest_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.company'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.paymentplans'),
        ),
    ]
