# Generated by Django 3.2.16 on 2023-02-12 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230212_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 20, 51, 30, 799992, tzinfo=utc)),
        ),
    ]
