# Generated by Django 3.2.16 on 2023-04-14 20:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20230414_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='problem_id',
            new_name='topic_id',
        ),
        migrations.AlterField(
            model_name='userextended',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 20, 5, 54, 176585, tzinfo=utc)),
        ),
    ]
