# Generated by Django 3.2.16 on 2023-04-16 20:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230414_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 20, 20, 39, 300126, tzinfo=utc)),
        ),
    ]
