# Generated by Django 3.2.16 on 2023-05-01 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_userextended_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 16, 30, 28, 310042, tzinfo=utc)),
        ),
    ]
