# Generated by Django 4.2 on 2023-04-29 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_userextended_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 19, 37, 15, 293556, tzinfo=datetime.timezone.utc)),
        ),
    ]
