# Generated by Django 4.2 on 2023-05-01 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_userextended_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 20, 43, 17, 259403, tzinfo=datetime.timezone.utc)),
        ),
    ]
